DATABASE_DIRECTORY = "../json"
DATA_DIRECTORY = "../data"
TRANSACTIONS_DIRECTORY = f"{DATA_DIRECTORY}/transactions/"
GLOBAL_SLEEPER_PLAYER_DATA_FILE = f"{DATABASE_DIRECTORY}/player_data.json"
GLOBAL_NFL_PLAYER_ID_FILE = f"{DATABASE_DIRECTORY}/player_id_table.csv"
APP_LOG_DIRECTORY = '../application_logs/'
LEAGUE_ID = "1075600889420845056"

